### ISSUE TITLE
Truthy and Falsy

### ISSUE THREAD

**Issue by rkfilali** [learn-co-curriculum/phase-0-pac-1-booleans#2]
In the lesson, Falsey is not the correct spelling , it should be falsy ( at least that is my impression)

**Comment by lizbur10** [comment]
Hi @rkfilali! Thanks for flagging this issue! I've done some research on this issue and there doesn't appear to be consensus about which spelling is correct/preferred. Given this, I'm going to leave it as is to maintain consistency with other lessons/labs. 

Thanks for contributing to the Flatiron curriculum 💙
