### ISSUE TITLE
Boolean not defined in REPL

### ISSUE THREAD

**Issue by Piter-Schark** [learn-co-curriculum/phase-0-pac-1-booleans#6]
### Canvas Link

https://learning.flatironschool.com/courses/6601/pages/boolean-expressions?module_item_id=510645

### Concern

There is a suggestion to try out Booleans in REPL.  But when I go to the REPL I have open, run to clear, it produces this:

Hint: hit control+c anytime to enter REPL.
 boolean(true)
ReferenceError: boolean is not defined
 boolean(false)
ReferenceError: boolean is not defined
 boolean(0)
ReferenceError: boolean is not defined
 

Maybe I've done something wrong.  But seems like an issue others would run into?

Thanks!  Really enjoying the pre-work so far.  Well explained, good baby steps chunks, excited for the course.  :)

**Comment by lizbur10** [comment]
Hi @Piter-Schark! The issue you're having is because JS is case sensitive - the REPL will recognized Boolean but not boolean.

Thanks for contributing to the Flatiron School curriculum, and thanks for the kind words 💙
